name = "fable-legacy"
compatibility_date = "2026-06-13"
pages_build_output_dir = "dist"

[[d1_databases]]
binding = "FABLE_LEGACY_DB"
database_name = "fable-legacy-db"
database_id = "09fd02cc-a247-41ac-8283-ad1e209a5944"
