INSERT OR IGNORE INTO submissions (
  id,
  project_name,
  project_url,
  author,
  contact,
  project_type,
  fable_usage,
  description,
  proof_url,
  status
) VALUES
(
  'intake-claude-fable-product-page',
  'Claude Fable product page',
  'https://www.anthropic.com/claude/fable',
  'Anthropic',
  '',
  'Research',
  'Official product page documenting Claude Fable 5 positioning, availability, pricing, and benchmark references.',
  'Research intake: official Anthropic model page that can supplement the existing launch post and documentation sources.',
  'https://www.anthropic.com/claude/fable',
  'pending'
),
(
  'intake-pebble-swift-metal',
  'Pebble',
  'https://github.com/thebriangao/pebble',
  'brian gao / ultrarunnerr',
  '',
  'Game',
  'Claude Fable 5 was directed to build a native macOS Swift and Metal block-survival game from scratch.',
  'Research intake: Reddit and GitHub evidence describe a 45k-line Swift/Metal voxel survival game with video, source code, and technical details. Needs final media and claims review before publication.',
  'https://www.reddit.com/r/ClaudeCode/comments/1u4fr9e/i_had_claude_fable_5_build_minecraft_from_scratch/',
  'pending'
),
(
  'intake-world-of-claudecraft',
  'World of Claudecraft',
  'https://github.com/levy-street/world-of-claudecraft',
  'ZYZZ JOBS / levy-street',
  '',
  'Game',
  'Claude Fable 5 was used to build an open-source browser MMORPG-style game.',
  'Research intake: X post includes gameplay media, a playable site, GitHub source, and author replies about Fable 5 ultracode usage. Needs playable-site review.',
  'https://x.com/maxpolaczuk/status/2065303310979277021',
  'pending'
),
(
  'intake-higgsfield-games',
  'Higgsfield Games',
  'https://higgsfield.ai/games-intro',
  'Higgsfield AI',
  '',
  'Tool',
  'Higgsfield says Claude Fable 5 powers a prompt-to-game workflow through Higgsfield MCP.',
  'Research intake: partner/product thread claims Fable 5-powered 2D and 3D multiplayer game generation. Comments include skepticism about whether demos are playable, so mark for careful verification.',
  'https://x.com/higgsfield/status/2065177172571214270',
  'pending'
),
(
  'intake-fable5-minecraft-html-test',
  'Fable5 Minecraft HTML Test',
  'https://github.com/Angais/Fable5-mc',
  'Angel / Angais',
  '',
  'Game',
  'Claude Fable 5 max effort generated an HTML and Three.js Minecraft-like test.',
  'Research intake: X evidence and GitHub source describe a browser block-world test with 3D rendering, game logic, and generated audio.',
  'https://x.com/lucas_flatwhite/status/2064595346819518882',
  'pending'
),
(
  'intake-dx12-realtime-cg-demo',
  'DirectX12 realtime CG demo',
  'https://github.com/neguse/dx12-demo-claude-fable-5',
  'neguse',
  '',
  'Demo',
  'Claude Fable 5 generated a realtime CG demo using C++, DirectX12, the C++ standard library, and minimal Windows APIs.',
  'Research intake: Japanese X post includes screenshot evidence and a GitHub repository; useful as a non-Web graphics example.',
  'https://x.com/neguse/status/2064622124153852305',
  'pending'
),
(
  'intake-fable5-world-demo',
  'Fable5 World Demo',
  'https://dc5fzrbo8ssfx.cloudfront.net/laas/',
  'Braffolk',
  '',
  'Demo',
  'Claude Fable 5 built a Three.js 3D world to test its capabilities.',
  'Research intake: GitHub repository explicitly attributes the 3D world demo to Claude Fable 5 and provides an online CloudFront demo.',
  'https://github.com/Braffolk/fable5-world-demo',
  'pending'
),
(
  'intake-mechanical-engine-platform',
  'Mechanical engine platform',
  'https://x.com/thebuggeddev/status/2065432072366243862',
  'The Bugged Dev',
  '',
  'Demo',
  'Claude Fable 5 generated a Three.js mechanical engine platform with custom geometry.',
  'Research intake: X post claims a one-prompt, zero-premade-asset Three.js mechanical model and includes video media. Needs media inspection before publication.',
  'https://x.com/thebuggeddev/status/2065432072366243862',
  'pending'
),
(
  'intake-kerbal-inspired-rocket-game',
  'Kerbal-inspired rocket game',
  'https://x.com/ChrissGPT/status/2065955584898158816',
  'Chris / ChrissGPT',
  '',
  'Game',
  'Claude Fable 5 was used to build a rocket construction and staged-separation game inspired by Kerbal Space Program.',
  'Research intake: X post claims a three-shot build with roughly 67k lines of code and includes gameplay video. Needs claim and media review.',
  'https://x.com/ChrissGPT/status/2065955584898158816',
  'pending'
),
(
  'intake-dream-starship-game-demo',
  'Dream starship game demo',
  'https://x.com/ChrissGPT/status/2065193150222663959',
  'Chris / ChrissGPT',
  '',
  'Game',
  'Claude Fable 5 generated an explorable starship demo with cockpit, crew quarters, interactions, lighting, and browser performance fixes.',
  'Research intake: X post claims Fable 5 screenshotted its own work and iterated until the browser demo reached 60fps. Includes video media.',
  'https://x.com/ChrissGPT/status/2065193150222663959',
  'pending'
),
(
  'intake-g1-manipulation-reachability',
  'G1 Manipulation reachability analysis',
  'https://x.com/dimensionalos/status/2065521741569663050',
  'Dimensional',
  '',
  'Optimization',
  'Claude Fable 5 integrated reachability analysis into a G1 humanoid manipulation framework.',
  'Research intake: X post reports a 5D arm capability map, self-collision checking, planning context creation dropping from 100ms to 62us, and dual-arm control. Needs technical validation.',
  'https://x.com/dimensionalos/status/2065521741569663050',
  'pending'
),
(
  'intake-codepilot-v056-fable-fixes',
  'CodePilot v0.56.0 fixes',
  'https://github.com/op7418/CodePilot/releases/tag/v0.56.0',
  'Guizang / guizang.ai',
  '',
  'Refactor',
  'Claude Fable 5 was used to find issues and complete part of the fixes in the CodePilot codebase.',
  'Research intake: Chinese developer release post says part of v0.56.0 was fixed by Claude Fable 5 after testing it on a large CodePilot codebase. Release link is available.',
  'https://x.com/op7418/status/2064572793124245998',
  'pending'
),
(
  'intake-platatlas-fieldops',
  'PlatAtlas FieldOps',
  'https://fieldops-87e.pages.dev/',
  'ClaudeFarms',
  '',
  'Tool',
  'Claude Fable 5 was used during a Build Day session to create the PlatAtlas FieldOps web app.',
  'Research intake: GitHub repository says the app was built live on Claude Fable 5 Build Day and includes a deployed Pages URL.',
  'https://github.com/ClaudeFarms/fieldops',
  'pending'
),
(
  'intake-fable-5-hunter',
  'Fable 5 Hunter',
  'https://github.com/dev-bricks/fable-5-hunter',
  'dev-bricks',
  '',
  'Tool',
  'A watcher monitors whether Claude Fable 5 is reachable again in Claude Code and sends notifications.',
  'Research intake: post-suspension ecosystem tool with Telegram, Discord, ntfy, and desktop notification support.',
  'https://github.com/dev-bricks/fable-5-hunter',
  'pending'
),
(
  'intake-donate-your-code',
  'Donate Your Code',
  'https://github.com/GeeveGeorge/donate-your-code',
  'GeeveGeorge',
  '',
  'Tool',
  'CLI for donating Claude Fable 5 transcript turns to a vetted CC0 dataset with scrubbing.',
  'Research intake: archive-adjacent project focused on preserving rare Claude Fable 5 interaction traces safely.',
  'https://github.com/GeeveGeorge/donate-your-code',
  'pending'
),
(
  'intake-fable-vs-opus-planning',
  'Fable vs Opus planning benchmark',
  'https://github.com/PedroLaRosa/fable-vs-opus-planning',
  'PedroLaRosa',
  '',
  'Benchmark',
  'Controlled head-to-head comparing Claude Fable 5 and Opus 4.8 planning the same feature through OpenSpec.',
  'Research intake: small community benchmark comparing time, cost, quality, and thoroughness for an explore-to-propose planning flow.',
  'https://github.com/PedroLaRosa/fable-vs-opus-planning',
  'pending'
),
(
  'intake-ml6-internal-codebase-review',
  'Fable 5 internal codebase review case',
  'https://www.ml6.eu/en/blog/anthropics-fable-5-is-out.-what-to-do-now',
  'ML6',
  '',
  'Benchmark',
  'ML6 compared Fable 5 and Opus 4.8 on an internal codebase release review and issue-finding task.',
  'Research intake: secondary benchmark with concrete cost, token, time, and release-blocking issue findings. Useful as an enterprise evaluation entry.',
  'https://www.ml6.eu/en/blog/anthropics-fable-5-is-out.-what-to-do-now',
  'pending'
);
